### PR TITLE
ENABLE_AVAHI is not included in WebServer

### LINKED ISSUE #995: Zeroconf does not work
- [x] I confirm that this is an issue rather than a question.

## Bug report

Zeroconf does not work as [advertised](https://docs.hyperion-project.org/en/api/Detect.html#zeroconf) (pun intended).

#### Steps to reproduce

Run `avahi-browse` on the local network, or on the machine hosting Hyperion:

```
(~) $ avahi-browse -r _hyperiond-http._tcp
```

... or ...

```
(~) $ avahi-browse -a | grep -i hyperion
```

#### What is expected?

Some form of output (as per diagram shown on [zeroconf instructions](https://docs.hyperion-project.org/en/api/Detect.html#zeroconf)).

#### What is actually happening?

No output.

#### System

```
Hyperion Server: 
- Build:       master (GitHub-f719f0b/838092e-1597257777)
- Build time:  Aug 19 2020 04:01:56
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.7
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51+ (WS: 32))
- Browser:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 
```

### PR DESCRIPTION
**Pull request by m-seker**
**Summary**

Fixes #995 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: libsrc/flatbufserver/FlatBufferServer.cpp [hunk 1]
```diff
@@ -93,14 +99,27 @@ void FlatBufferServer::startServer()
...
-	    }
+		if(!_server->listen(QHostAddress::Any, _port))
+		{
+			Error(_log,"Failed to bind port %d", _port);
+		}
+		else
+		{
+			Info(_log,"Started on port %d", _port);
+#ifdef ENABLE_AVAHI
+			if(_serviceRegister == nullptr)
```
Comment (m-seker) [inline libsrc/flatbufserver/FlatBufferServer.cpp:110]: @Paulchen-Panther This is documented but not implemented. I am not missing anything right ?

Comment (Paulchen-Panther) [reply libsrc/flatbufserver/FlatBufferServer.cpp:110]: @brindosch made the last change to the AVAHI interface. Maybe you should check his PR to see if he has deactivated something that is missing now.
https://github.com/hyperion-project/hyperion.ng/pull/738
I can't say much without looking deeper because @brindosch introduced the AVAHI interface. Sorry

Comment (m-seker) [reply libsrc/flatbufserver/FlatBufferServer.cpp:110]: Avahi support seems to be implemented before that PR and I don't see FlatBuffer advertisement there as well. Probably forgotten. 
Thanks.

**Comment by Paulchen-Panther** [comment]
@m-seker Ready?
