### PR TITLE
Bugfix/leaks - Possibly fixes #722

### LINKED ISSUE #722: Hyperiond memory leak on RPi3B+Arduino
- [x] I confirm that this is an issue rather than a question.

## Bug report
On my setup hyperiond (daemon?) memory usage starts out very low and then gradually grows until system crashes/grinds to a halt due to running out of memory. My setup is a RPi3B running LibreElec, an Arduino Nano and WS2812B LEDs. I had the same issue with old Hyperion.

#### Steps to reproduce
Simply leave hyperion-ng running with normal usage, changing effects a few times a day (from HDMI when playing media to mood lightning effects etc.). As of writing this the system has been up for 6 days and hyperiond memory usage is at about ~600MB. 

#### What is expected?
That hyperiond memory usage would stay about the same over time.

#### What is actually happening?
hyperiond memory usage grows endlessly until system crash.

#### System

```
Hyperion Server: 
- Build:       (HEAD detached at bec6c495) (brindosch-0ff09987/bec6c495-1583074045)
- Build time:  Mar  1 2020 15:18:20
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.3
- UI Lang:     auto (BrowserLang: sv-SE)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: LibreELEC (official): 9.2.0
- Arch:         arm
- Kernel:       linux (4.19.83 (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0 
```

### PR DESCRIPTION
**Pull request by m-seker**
**Summary**

Fix some memory leaks.

Possibly fixes https://github.com/hyperion-project/hyperion.ng/issues/722.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: src/hyperiond/hyperiond.cpp [hunk 1]
```diff
@@ -170,29 +170,29 @@ void HyperionDaemon::freeObjects()
 	delete _jsonServer;
 	_flatBufferServer->thread()->quit();
 	_flatBufferServer->thread()->wait(1000);
-	_flatBufferServer->deleteLater();
-	_flatBufferServer->thread()->deleteLater();
+	delete _flatBufferServer->thread();
```
Comment (m-seker) [inline src/hyperiond/hyperiond.cpp:173]: Event loop is already finished at that point, hence the scheduled events will not work.

File: include/utils/Image.h [hunk 2]
```diff
@@ -256,6 +256,7 @@ class Image
 	{
 		_width = 1;
 		_height = 1;
+		delete[] _pixels;
```
Comment (m-seker) [inline include/utils/Image.h:259]: This can be the root cause of growing leak

**Comment by Paulchen-Panther** [comment]
Thank you for your detailed descriptions.
