### PR TITLE
LED Device Features, Fixes and Refactoring

### LINKED ISSUE #727: Add YeeLight LedDevice support
#### What problem does this feature solve?

Add YeeLight as an additional device type.

#### What does the proposed API look like?

N/A

#### How should this be implemented in your opinion?

Using the offocial YeeLight API

#### Are you willing to work on this yourself?

Yes.

### LINKED ISSUE #755: Allow to reopen devices after disable or suspend
#### What problem does this feature solve?

Currently, devices do not always handle the situation properly, if hyperion is
- resumed after being suspended (e.g. CoreElec)
- enabled after a longer time and a  device's state is not known/defined
(e.g. Philips Hue or Nanoleaf was turned off or used otherwise).

#### How should this be implemented in your opinion?

- Clear differentiation between starting and stopping a device
- When switching on a device (after disable device, disable hyperion or system suspend), 
open the device and/or set appropriate device mode (for REST-Devices).

#### Are you willing to work on this yourself?

I already started.

### LINKED ISSUE #859: Hyperion doesn’t work with USB SSD boot RPi4, works with same setup with SD card
- [x] I confirm that this is an issue rather than a question.

## Bug report
Ok, I’ll try to be short. Around one month back I install Hyperion ng from here, CompileHowto and use manual was under the script. When I try script it stop somewhere in the middle. But manually it works. After some fighting and googling, I found everything and it’s start working!

So I enjoy it one month on my Raspberry 4 and today I update eeprom for USB boot and connect SSD. On this SSD I use same system. Make manual installation of Hyperion ng like before. See all the same in webui by what I remember and nothing. After I try to export settings from SD card Hyperion (I remove USB SSD and insert old SD card I use maybe one hour ago and here it’s still working) and after I remove SD card, put back SSD and import this settings. But nothing change. Still doesn’t work. 

I try ls /dev if something change before and after reconnecting LED. Only two thing changing, ttyUSB0 and serial. I use adalight USB, so before and now I use ttyUSB0, before it works, now doesn’t. USB for LED stay same. Only thing what I change is remove USB SSD and insert old SD card and it’s working. Remove SD card and insert SSD in USB and it’s not working. 

SD card show me LED device is green. SSD isn’t green. 
Here is debug log from Hyperion. Sorry I don’t paste it nicely. I write this from phone and I don’t know how to make nice block...

 [hyperiond EFFECTFILES] (INFO) 39 effects loaded from directory :/effects/
 [hyperiond EFFECTFILES] (INFO) 22 effect schemas loaded from directory :/effects/schema/
 [hyperiond EFFECTFILES] (INFO) 0 effects loaded from directory /root/.hyperion/custom-effects
 [hyperiond SettingsManager] (DEBUG) (SettingsManager.cpp:108:SettingsManager()) Settings database initialized
 [hyperiond BLACKBORDER] (DEBUG) (BlackBorderProcessor.cpp:65:handleSettingsUpdate()) Set mode to: osd
 [hyperiond ComponentRegister] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Blackborder detector: enabled
 [hyperiond DAEMON] (INFO) set screen capture device to 'dispmanx'
 [hyperiond DISPMANXGRABBER] (DEBUG) (Grabber.cpp:35:setVideoMode()) Set videomode to 0
 [hyperiond DISPMANXGRABBER] (INFO) Display opened with resolution: 1920x1080
 [hyperiond DISPMANXGRABBER] (DEBUG) (Grabber.cpp:95:setWidthHeight()) Set new width: 160, height: 90 for capture
 [hyperiond DAEMON] (INFO) DISPMANX frame grabber created
 [hyperiond V4L2:auto] (DEBUG) (Grabber.cpp:35:setVideoMode()) Set videomode to 0
 [hyperiond V4L2:auto] (INFO) Signal threshold set to: {12, 12, 12}
 [hyperiond V4L2:auto] (INFO) Signal detection is now disabled
 [hyperiond V4L2:auto] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 [hyperiond DAEMON] (DEBUG) (hyperiond.cpp:498:handleSettingsUpdate()) V4L2 grabber created
 [hyperiond JSONSERVER] (DEBUG) (JsonServer.cpp:27:JsonServer()) Created instance
 [hyperiond JSONSERVER] (INFO) Started on port 19444
 [hyperiond LEDDEVICE] (INFO) LedDevice 'adalight' found.
 [hyperiond ComponentRegister] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Smoothing: enabled
 [hyperiond LEDDEVICE] (DEBUG) (LedDeviceAdalight.cpp:56:init()) Adalight header for 256 leds: Ada 0x00 0xff 0xaa
 [hyperiond LEDDEVICE] (INFO) Opening UART: /dev/ttyUSB0
 [hyperiond FLATBUFCONNECTION] (INFO) Connecting to Hyperion: 127.0.0.1:19401
 [hyperiond PROTOSERVER] (INFO) Started on port 19445
 [hyperiond EFFECTENGINE] (INFO) Run effect "Rainbow swirl fast" on channel 0
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:33:initServer()) Initialize Webserver
 [hyperiond FLATBUFSERVER] (INFO) Started on port 19400
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:33:initServer()) Initialize Webserver
 [hyperiond EFFECTENGINE] (DEBUG) (EffectEngine.cpp:188:runEffectScript()) Start the effect: name [Rainbow swirl fast], smoothCfg [2]
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:158:registerInput()) Register new input 'System/EFFECT' with priority 0 as inactive
 [hyperiond HYPERION] (INFO) Initial foreground effect 'Rainbow swirl fast' started
 [hyperiond EFFECTENGINE] (INFO) Run effect "Warm mood blobs" on channel 254
 [hyperiond EFFECTENGINE] (DEBUG) (EffectEngine.cpp:188:runEffectScript()) Start the effect: name [Warm mood blobs], smoothCfg [2]
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:158:registerInput()) Register new input 'System/EFFECT' with priority 254 as inactive
 [hyperiond HYPERION] (INFO) Inital background effect 'Warm mood blobs' started
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:158:registerInput()) Register new input 'System/GRABBER' with priority 250 as inactive
 [hyperiond ComponentRegister] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Framegrabber: enabled
 [hyperiond Dispmanx] (DEBUG) (GrabberWrapper.cpp:49:start()) Grabber start()
 [hyperiond BOBLIGHT] (DEBUG) (BoblightServer.cpp:28:BoblightServer()) Instance created
 [hyperiond HYPERION] (INFO) Hyperion instance 'First LED Hardware instance' has been started
 [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'adalight' signals error: 'Invalid serial device name: [/dev/ttyUSB0]!'
 [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'adalight' signals error: 'Error opening device!'
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:91:handleSettingsUpdate()) Apply Webserver settings
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:109:handleSettingsUpdate()) Set document root to: :/webconfig
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:91:handleSettingsUpdate()) Apply Webserver settings
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:109:handleSettingsUpdate()) Set document root to: :/webconfig
 [hyperiond WEBSERVER] (INFO) Started on port 8090 name 'Hyperion Webserver'
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:238:setInputImage()) Priority 250 is now active
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:333:setCurrentTime()) Set visible priority to 0
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:175:handleSettingsUpdate()) Setup SSL certificate
 [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:191:handleSettingsUpdate()) Setup private SSL key
 [hyperiond WEBSERVER] (INFO) Started on port 8092 name 'Hyperion Webserver'
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:238:setInputImage()) Priority 0 is now active
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:198:setInput()) Priority 254 is now active
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:298:setCurrentTime()) Timeout clear for priority 0
 [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:333:setCurrentTime()) Set visible priority to 250
 [hyperiond WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.144.90
 [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:103:handleInstanceSwitch()) Client '::ffff:192.168.144.90' switch to Hyperion instance 0
 [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:1047:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.144.90

#### Steps to reproduce
Install Hyperion with working setup same but on USB drive. 

#### What is expected?
It will work sans like on SD card. 

#### What is actually happening?
LED doesn’t work on SSD but work on SD card. 

#### System

Doesn’t work:

Hyperion Server: 
- Build:       master (GitHub-922420bb/6cf9dfaa-1593464112)
- Build time:  Jun 30 2020 16:03:00
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.6
- UI Lang:     en (BrowserLang: cs)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1 

Working:

Hyperion Server: 
- Build:       master (Sersch-0c925f1e/85e2bc9f-1590681442)
- Build time:  May 29 2020 08:41:49
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.6
- UI Lang:     en (BrowserLang: cs)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.118-v7l+ (WS: 32))
- Browser:      Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

Features, Fixes and Refactoring around LED Devices

### Added

New Devices
- Yeelight support incl. device discovery and setup-wizard
- WLED as own device and pre-configuration

Additional device related capabilities
- discover, getProperties, identify, store/restore state and power-on/off 
available for Philips-Hue, Nanoleaf, Yeelight, partially for Rs232 / USB (Hid)
- New device capabilities are accessible via JSON-API
- New REST-API wrapper class in support of network devices, e.g. Philips Hue, Nanoleaf and WLED
- Flexible ssdp-Discovery incl. RegEx matching and filtering

Documentation
- Process workflow for LED-Devices
- Documentation of device classes & methods
- Code template for new LED-Devices available

### Changed
- LED-Device workflow changed allowing proper suspend/resume & disable/enable scenarios
- Network LED-Devices will stop sending packages when disabled
- Rs232 Provider fully reworked and changed to synchronous writes
- Rs232 configuration via portname and system location (/dev/ style), auto detection is not case-sensitive any longer
- Additional error handling depending on device type
- Add Windows compatibility incl. moving to Qt functions
- Add compatibility for different Qt versions

### Fixed
- AtomOrb: Buffer length fix and new configuration validations
- Added missing DMX SubTypes to configuration
- Code clean-ups

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [X] Feature
- [ ] Code style update
- [X] Refactor
- [X] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

Resolves #755
Resolves #727 
Resolves #859

### CODE REVIEW

**Comment by tpmodding** [comment]
❤️ big update! thanks for this one :) can not wait to release this one

**Comment by tihoangyeudau** [comment]
Please fix rpi recognize pi cam on hyperion.ng!

**Comment by tihoangyeudau** [comment]
Wled and other udp devices works well but only udpe131 does not work anymore. please check it again

**Comment by Lord-Grey** [comment]
@tihoangyeudau Thanks for testing  and confirming the WLED and other UDP Devices work well.
I found the problem on udpe131. When no CID is given and one is generated, I missed to set the device in the state that initialization was done successfully. If you configure a cid (using the one generated "0c73dd1d-fac9-4784-adeb-a5bb28fac110"), the device should work. I am going to fix it later....

**Comment by tihoangyeudau** [comment]
> @tihoangyeudau Thanks for testing and confirming the WLED and other UDP Devices work well.
> I found the problem on udpe131. When no CID is given and one is generated, I missed to set the device in the state that initialization was done successfully. If you configure a cid (using the one generated "0c73dd1d-fac9-4784-adeb-a5bb28fac110"), the device should work. I am going to fix it later....

yes, thank you for your try. your fork works very smoothly and fastly. wait for wled winzart and fixed udpe131

File: libsrc/leddevice/dev_net/LedDeviceWled.cpp [hunk 1]
```diff
@@ -0,0 +1,301 @@
...
+
+		//If host not configured the init fails
+		if ( address.isEmpty() )
+		{
+			this->setInError("No target hostname nor IP defined");
+			return false;
+		}
+		else
+		{
+			#if (QT_VERSION >= QT_VERSION_CHECK(5, 14, 0))
```
Comment (m-seker) [inline libsrc/leddevice/dev_net/LedDeviceWled.cpp:82]: Maybe we should encapsulate this in an internal string helper library instead of repeating those if elses everytime we need a split

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp [hunk 2]
```diff
@@ -0,0 +1,1503 @@
...
+#include <QDateTime>
+
+#include <chrono>
+#include <thread>
+
+static const bool verbose  = false;
+static const bool verbose3  = false;
+
+// Constants
+const int WRITE_TIMEOUT	= 1000;			 // device write timeout in ms
```
Comment (m-seker) [inline libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:21]: What about this for unit type safety ?

    constexpr std::chrono::milliseconds WRITE_TIMEOUT{1000};

Then you can use ````WRITE_TIMEOUT.count()```` to get the value in msecs.

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp [hunk 3]
```diff
@@ -0,0 +1,1503 @@
...
+const int READ_TIMEOUT	= 1000;			 // device write timeout in ms
+const int CONNECT_TIMEOUT = 1000;		 // device connect timeout in ms
+const int CONNECT_STREAM_TIMEOUT = 1000; // device streaming connect timeout in ms
+
+static const bool TEST_CORRELATION_IDS  = false; //Ignore, if yeelight sends responses in different order as request commands
```
Comment (m-seker) [inline libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:26]: Instead of marking all those variables as static, what about putting them in an anonymous namespace ? It will do the same job. Using static keyword in this context is more of a C style.

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp [hunk 4]
```diff
@@ -0,0 +1,1503 @@
...
+	_name = hostname;
+
+}
+
+YeelightLight::~YeelightLight()
+{
+	log (3,"~YeelightLight()","" );
+	if ( _tcpSocket != nullptr)
+	{
+		_tcpSocket->deleteLater();
```
Comment (m-seker) [inline libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:118]: Is there a reason for not using ````delete```` directly ? Using ````deleteLater```` is something I need mostly when I need to delete the ````QObject::sender()```` object inside a slot. 

This will also do the job but there is a downside of using this method : It can make debugging harder in some specific cases as there will still be a code waiting to be executed even after the destructor finishes.

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp [hunk 5]
```diff
@@ -0,0 +1,1503 @@
...
+	else
+	{
+		// Minimum one Yeelight device is working, continue updating devices
+		rc = 0;
+	}
+
+	//DebugIf(verbose, _log, "rc [%d]", rc );
+
+	return rc;
+}
```
Comment (m-seker) [inline libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:1503]: 1500 lines for a single CPP hints that some functionality needs to be moved elsewhere.

File: libsrc/leddevice/dev_net/ProviderRestApi.cpp [hunk 6]
```diff
@@ -0,0 +1,242 @@
...
+	_path.clear();
+	appendPath (_path, path );
+}
+
+void ProviderRestApi::appendPath ( const QString &path )
+{
+	appendPath (_path, path );
+}
+
+void ProviderRestApi::appendPath (QString& path, const QString &appendPath)
```
Comment (m-seker) [inline libsrc/leddevice/dev_net/ProviderRestApi.cpp:60]: it can be a ````const```` method

File: libsrc/leddevice/dev_net/ProviderRestApi.cpp [hunk 7]
```diff
@@ -0,0 +1,242 @@
...
+{
+	_fragment = fragment;
+}
+
+void ProviderRestApi::setQuery(const QUrlQuery &query)
+{
+	_query = query;
+}
+
+QUrl ProviderRestApi::getUrl()
```
Comment (m-seker) [inline libsrc/leddevice/dev_net/ProviderRestApi.cpp:99]: it can be a ````const```` method

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp (hunk 4 above)
Comment (m-seker) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:118]: See another possible pitfall : https://github.com/hyperion-project/hyperion.ng/pull/863/files#r449817735

**Comment by Lord-Grey** [comment]
> > @tihoangyeudau Thanks for testing and confirming the WLED and other UDP Devices work well.
> > I found the problem on udpe131. When no CID is given and one is generated, I missed to set the device in the state that initialization was done successfully. If you configure a cid (using the one generated "0c73dd1d-fac9-4784-adeb-a5bb28fac110"), the device should work. I am going to fix it later....
> 
> yes, thank you for your try. your fork works very smoothly and fastly. Waiting for wled winzart and fixed udpe131

Fix is available.

**Comment by tihoangyeudau** [comment]
Ok bro

File: libsrc/leddevice/LedDeviceWrapper.cpp [hunk 8]
```diff
@@ -134,6 +134,11 @@ unsigned int LedDeviceWrapper::getLedCount() const
 	return _ledDevice->getLedCount();
 }
 
+const bool & LedDeviceWrapper::enabled()
```
[the remark this answers is not in the document]
Comment (Lord-Grey) [reply libsrc/leddevice/LedDeviceWrapper.cpp:137]: I agree, returning  primitive should not be done via reference. I do currently not see any reason why it should be by reference.

File: libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h [hunk 9]
```diff
@@ -19,47 +20,73 @@
...
+
 	///
-	/// @return Zero on success else negative
+	/// @brief Writes the RGB-Color values to the LEDs.
 	///
-	virtual int write(const std::vector<ColorRgb>& ledValues) override;
+	/// @param[in] ledValues The RGB-color per LED
+	/// @return Zero on success, else negative
+	///
+	virtual int write(const std::vector<ColorRgb> & ledValues) override;
```
[the remark this answers is not in the document]
Comment (Lord-Grey) [reply libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h:81]: If virtual or not is there does not make any difference, or ? It may just outline the function is virtual from a documentation perspective....

_"If some member function vf is declared as virtual in a class Base, and some class Derived, which is derived, directly or indirectly, from Base, has a declaration for member function with the same
    name
    parameter type list (but not the return type)
    cv-qualifiers
    ref-qualifiers 
**Then this function in the class Derived is also virtual (whether or not the keyword virtual is used in its declaration)** and overrides Base::vf (whether or not the word override is used in its declaration). "_

File: libsrc/leddevice/dev_net/LedDeviceWled.cpp (hunk 1 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceWled.cpp:82]: Good idea. You would like to have a go and put it under libsrc/utils/QStringutils.h ?

File: libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (m-seker) [reply libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h:81]: It doesn't make any difference, just a matter of preference.

https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html

Go as you wish :)

File: libsrc/leddevice/dev_net/LedDeviceWled.cpp (hunk 1 above)
Comment (m-seker) [reply libsrc/leddevice/dev_net/LedDeviceWled.cpp:82]: Maybe later :)

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp (hunk 2 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:21]: Done.

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp (hunk 3 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:26]: "Using static keyword in this context is more of a C style."
I though not using #define, but having even types is more c++, but if namespace, if the way to go, happy to have a look at.

Comment (m-seker) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:26]: It has some advantages too : https://stackoverflow.com/questions/4422507/superiority-of-unnamed-namespace-over-static

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp (hunk 4 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:118]: Removed deleteLater in various LedDevice files.

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp (hunk 5 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:1503]: Fair point. I may need to have the individual YeelightLight class separate from the YeelightDevice... (then I could move ~1000 lines to a separate ccp. Need the to think about filenaming and where to put those sub-object classes. PhilipsHueLights would be the 2nd candidate...

Plus change my readability style....

File: libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (Lord-Grey) [reply libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h:81]: You have a point. But I am hesitant to update all header files again :-(
Maybe there is an auto-cleanup function....

[the remark this answers is not in the document]
Comment (m-seker) [reply libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h:81]: Yeah those should be done via clang-tidy. No need for manual cleanup. These can be fixed all at once when we setup a proper clangtidy file across the project.

File: libsrc/leddevice/dev_net/ProviderRestApi.cpp (hunk 6 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/ProviderRestApi.cpp:60]: Correct. Updated!

File: libsrc/leddevice/dev_net/ProviderRestApi.cpp (hunk 7 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/ProviderRestApi.cpp:99]: Update Done.

Thanks for all the helpful feedback!!!

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp (hunk 3 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:26]: Does this mean we should review the static functions, too?
e.g. 
LedDeviceWrapper
	static const QJsonObject getLedDeviceSchemas();

Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:26]: Updates done on all LedDevice files

File: libsrc/leddevice/dev_net/LedDeviceWled.cpp (hunk 1 above)
Comment (Lord-Grey) [reply libsrc/leddevice/dev_net/LedDeviceWled.cpp:82]: I added a QStringUtil.h with an inline function.
Please have a look when i commit later....

File: libsrc/leddevice/dev_net/LedDeviceYeelight.cpp (hunk 3 above)
Comment (m-seker) [reply libsrc/leddevice/dev_net/LedDeviceYeelight.cpp:26]: > Does this mean we should review the static functions, too?
> e.g.
> LedDeviceWrapper
> static const QJsonObject getLedDeviceSchemas();

maybe with the time...

**Comment by Paulchen-Panther** [comment]
Wolltest du hier noch aufräumen oder ist dieser PR fertig?
