### PR TITLE
Start SmartPointers

### LINKED ISSUE #981: Improve exception safety with smart pointers
Would you like to [wrap any pointer data members](https://github.com/hyperion-project/hyperion.ng/blob/c00d8e62fb5a57f57a142fcd51ad5822c8bef544/src/hyperiond/hyperiond.cpp#L63 "Update candidate: HyperionDaemon class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

- Started using SmartPointers (#981)
- Refactored HyperionDaemon using SmartPointer and restructured code
- Start Grabbers via template

Note: PR includes main changes of #1678

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [X] Code style update
- [X] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [X] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**
Fixes #981

### CODE REVIEW

**Review by Paulchen-Panther — APPROVED** [review]

File: libsrc/hyperion/GrabberWrapper.cpp [hunk 1]
```diff
@@ -56,6 +56,8 @@ GrabberWrapper::GrabberWrapper(const QString& grabberName, Grabber * ggrabber, i
 
 GrabberWrapper::~GrabberWrapper()
 {
+	_timer->stop();
+	delete _timer;
```
Comment (elfring) [inline libsrc/hyperion/GrabberWrapper.cpp]: :thought_balloon: Should such an operation be performed by [a smart pointer](https://doc.qt.io/qt-6/qscopedpointer.html "Using a QScopedPointer class?")?

Comment (Lord-Grey) [reply libsrc/hyperion/GrabberWrapper.cpp]: Yes. That would work.

Unfortunately, we are only two developers currently and do have the bandwidth cleaning up the whole code base proactively now. Esp. Like for the sample where the code correctly works and there is limited immediate benefit.

Comment (elfring) [reply libsrc/hyperion/GrabberWrapper.cpp]: How do you think about to avoid redundant code a bit more? :thinking:

Comment (Lord-Grey) [reply libsrc/hyperion/GrabberWrapper.cpp]: I am not sure, if I get your question…
In case of new additions or refactoring code,  now Smartpointers can be used to avoid additional boilerplate and make code more maintainable.
Nevertheless, there are more serious problems out there than removing working statements like above.
E.g. the grabber design is not consistent any longer and not every grabber is scalable.
Spending refactoring effort in that light would make great sense including removing redundant code.

We would be happy, if you and others would give us a helping hand in cleaning up current code and/or designs.
